name: sistema_proveedores_client
description: "Frontend oficial del Sistema de Gestión de Proveedores. Implementado con Flutter y Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Actualizado a versiones estables de 2026

dependencies:
  flutter:
    sdk: flutter
  # ... otras dependencias
  lottie: ^3.1.0  # <--- AGREGA ESTA LÍNEA

  # --- ICONOGRAFÍA & ASSETS ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # --- UI & ANIMACIONES ---
  rive: ^0.13.20
  google_fonts: ^6.2.1
  # Senior Tip: Para animaciones sutiles de entrada de widgets
  flutter_staggered_animations: ^1.0.0

  # --- NETWORKING & SEGURIDAD ---
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.3

  # --- STATE MANAGEMENT & UTILITARIOS ---
  provider: ^6.1.1
  logger: ^2.4.0
  # FUNDAMENTAL para Clean Architecture (comparación de objetos/modelos)
  equatable: ^2.0.5
  # CRÍTICO para formateo de moneda (S/.) y fechas en Perú
  intl: ^0.19.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Recomendado: Reglas de linter más estrictas para mentalidad Senior
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # REGISTRO DE FUENTES (Optimizado)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

  # REGISTRO DE ASSETS (Limpio y Jerárquico)
  assets:
    - assets/fonts/
    - assets/samples/animations/
    - assets/samples/ui/rive_app/rive/
    - assets/samples/ui/rive_app/images/
    # Ruta específica para tu avatar solicitado
    - assets/samples/ui/rive_app/images/avatars/
    - assets/samples/ui/rive_app/images/backgrounds/
    - assets/samples/ui/rive_app/images/topics/
    - assets/samples/animations/animation_loader.json
