name: sistema_proveedores_client
description: "Frontend oficial del Sistema de Gestión de Proveedores. Implementado con Flutter y Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # --- ICONOGRAFÍA ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1      # Para los iconos .svg de la plantilla

  # --- UI & ANIMACIONES ---
  rive: ^0.13.20              # Motor para tus archivos .riv (shapes, check, etc.)
  google_fonts: ^6.2.1

  # --- NETWORKING & SEGURIDAD ---
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.3

  # --- STATE MANAGEMENT & ARQUITECTURA ---
  provider: ^6.1.1
  logger: ^2.4.0

  # --- UTILIDADES ---
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 1. REGISTRO DE FUENTES (Basado en tu carpeta assets/fonts)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

  # 2. REGISTRO DE ASSETS (Rutas exactas según tu imagen)
  # Nota: Flutter no es recursivo, hay que declarar cada subcarpeta que contenga archivos.
  assets:
    - assets/fonts/
    - assets/samples/animations/
    - assets/samples/ui/rive_app/
    - assets/samples/ui/rive_app/rive/
    - assets/samples/ui/rive_app/images/
    - assets/samples/ui/rive_app/images/avatars/
    - assets/samples/ui/rive_app/images/backgrounds/
    - assets/samples/ui/rive_app/images/topics/
