name: sistema_proveedores_client
description: "Frontend oficial del Sistema de Gestión de Proveedores. Implementado con Flutter y Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # --- ICONOGRAFÍA ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1      # Indispensable para iconos vectoriales sin pérdida de calidad

  # --- UI & ANIMACIONES (Experiencia de Usuario) ---
  rive: ^0.13.20              # Motor de animaciones interactivas (State Machines)
  google_fonts: ^6.2.1        # Gestión dinámica de tipografías modernas

  # --- NETWORKING & SEGURIDAD (Conexión Laravel) ---
  dio: ^5.4.0                 # Cliente HTTP robusto con interceptores (estilo Axios)
  flutter_secure_storage: ^9.0.0 # Almacenamiento cifrado para JWT/Tokens de Laravel
  connectivity_plus: ^6.0.3   # Para detectar si el usuario tiene internet antes de peticiones

  # --- STATE MANAGEMENT & ARQUITECTURA ---
  provider: ^6.1.1            # Inyección de dependencias y gestión de estado simple
  logger: ^2.4.0              # Logs profesionales para debugear la API en consola

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints recomendados para mantener Clean Code y SOLID
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # CONFIGURACIÓN DE ASSETS
  # Recuerda crear estas carpetas en la raíz de tu proyecto
  assets:
    - assets/
    - assets/animations/      # Para tus archivos .riv de Rive
    - assets/icons/           # Para tus archivos .svg
